In [ ]:
# 我是大标题

# 我是大标题

In [ ]:
我是**粗体字**

我是*斜体字*

我被~~删除~~了

https://www.bilibili.com/

[我的主页地址](https://www.bilibili.com/)

In [ ]:
![图片链接](https://ts1.cn.mm.bing.net/th/id/R-C.823270fc68b9c58f0d9b3feb92b7b172?rik=aubbEBMSC86e%2bw&riu=http%3a%2f%2fimg95.699pic.com%2fphoto%2f50038%2f1181.jpg_wh860.jpg&ehk=iQboj4JMLLfDitOL7VJtSktED0AE%2f7Fyxfik0GTJkyQ%3d&risl=&pid=ImgRaw&r=0)

这是一个公式： $y=x+3$

这是独占一行的公式： $$y=x+3$$

In [43]:
import numpy as np

In [7]:
np.concatenate([arr1, arr2])    # 连接数组，数据类型会调制统一

NameError: name 'arr1' is not defined

In [22]:
# sorted函数，传入列表后，会返回一个新的排序号的列表
list1 = [5, 2, 7, 88, 45]
sorted_list = sorted(list1)   #————不改变原始列表list1，返回新列表
print(sorted_list)

[2, 5, 7, 45, 88]

In [11]:
# sort方法，调用后，该列表的元素都会被排序好
list1 = [5, 2, 7, 88, 45]
list1.sort()   #————不会返回新列表，改变原始列表list1
print(list1)

[2, 5, 7, 45, 88]

In [19]:
list1 = [5, 2, 7, 88, 45]
print(list1[2])
print(list1[-2])
print(list1[1:4])  # 左开右闭
print(list1[2:])

7
88
[2, 7, 88]
[7, 88, 45]

In [21]:
arr = np.array([5, 2, 7, 88, 45])
print(arr[arr > 6])                   # 广播机制
print(arr[ (arr > 6)&( arr <50)] )

[ 7 88 45]
[ 7 45]

In [3]:
import pandas as pd    # pandas 数据结构

In [26]:
s1 = pd.Series([5, 17, 3, 226, 31])

In [27]:
print(s1)
print(s1.values)
print(s1.index)

0      5
1     17
2      3
3    226
4     31
dtype: int64
[  5  17   3 226  31]
RangeIndex(start=0, stop=5, step=1)

In [30]:
print(s1[2])
print("-------------")
print(s1[1:3])

3
-------------
1    17
2     3
dtype: int64

In [34]:
s10 = pd.Series([5, 17, 3, 226, 31],
              index=['a', 'd', "v", "e", 'r'])
s10

a      5
d     17
v      3
e    226
r     31
dtype: int64

In [37]:
print(s10['e'])    #  名为“标签索引”
print(s10["v":"r"])  # 结束值在标签索引中包含在内
print(s10[-1])     #  名为“位置索引”

# 若标签索引也为整数值int时，则索引取值时按照标签，切片时按照位置

226
v      3
e    226
r     31
dtype: int64
31

In [44]:
# loc -用标签索引，进行取值或切片；包含最后的值
# iloc -用位置索引，进行取值或切片；不包含最后的值

# 与：&    或：|    非：~
s2 = pd.Series([1, 2, 3, 4, 5], index=[5, 4, 3, 2, 1])
s2

5    1
4    2
3    3
2    4
1    5
dtype: int64

**输出s2里按位置顺序排在第2个的元素**

In [41]:
s2.iloc[1]

2

**输出s2里按标签对应从5到3（包括3）范围内的元素**

In [43]:
s2.loc[5:3]

5    1
4    2
3    3
dtype: int64

In [45]:
s3 = pd.Series({"小李": 82, "小陈": 93, "小张": 91, "小曾": 78, "小邓": 68})
s3

小李    82
小陈    93
小张    91
小曾    78
小邓    68
dtype: int64

In [47]:
s3["小张"] = 95
# 最好的写法： s3.iloc["小张"] = 95
s3

小李    82
小陈    93
小张    95
小曾    78
小邓    68
dtype: int64

In [48]:
s3 > 80

小李     True
小陈     True
小张     True
小曾    False
小邓    False
dtype: bool

In [50]:
s3[(s3 > 80) & (s3 < 90)]

小李    82
dtype: int64

**apply 不改变原始Series**
###### lambda 参数 : 返回值   实例： lambda x : x*x

# Series的用法

In [53]:
# 创建a1，包含元素[92, 67, 70, 88, 76]及对应索引["小明", "小红", "小杰", "小丽", "小华"]
# 创建a2，包含元素[95, 85, 60, 79, 76]及对应索引["小明", "小杰", "小宇", "小娟", "小彤"]，创建后打印a1和a2
a1 = pd.Series([92, 67, 70, 88, 76], index=["小明", "小红", "小杰", "小丽", "小华"])
a2 = pd.Series([95, 85, 60, 79, 76], index=["小明", "小杰", "小宇", "小娟", "小彤"])
print(a1)
print(a2)

小明    92
小红    67
小杰    70
小丽    88
小华    76
dtype: int64
小明    95
小杰    85
小宇    60
小娟    79
小彤    76
dtype: int64

In [55]:
# 让a1和a2的相同索引元素之间进行相加，若无法找到对应索引的值则将缺失值用0代替
a1.add(a2, fill_value=0)

小丽     88.0
小华     76.0
小娟     79.0
小宇     60.0
小彤     76.0
小明    187.0
小杰    155.0
小红     67.0
dtype: float64

In [56]:
# 输出s1的统计学相关数据，包括最大值、最小值、平均值、标准差
a1.describe()

count     5.000000
mean     78.600000
std      10.990905
min      67.000000
25%      70.000000
50%      76.000000
75%      88.000000
max      92.000000
dtype: float64

In [57]:
# 把a1更新为所有数字加5后的结果，并进行输出
a1 + 5   # ————这样写只会输出结果，但不会改变a1

小明    97
小红    72
小杰    75
小丽    93
小华    81
dtype: int64

In [59]:
# 根据规则，输出一个新的Series，包含a1里各个学生成绩所对应的等级
def get_grade_from_score(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return '不及格'

In [60]:
get_grade_from_score(55)

'不及格'

In [61]:
a1.apply(get_grade_from_score)    # apply相当于一个高阶函数，在apply里调用函数

小明    A
小红    D
小杰    C
小丽    B
小华    C
dtype: object

# DataFrame的用法

In [62]:
# DataFrame可以看成由Series组成的字典
# df[] 为列的索引
# df.loc[]   df.iloc[]  为行的索引

In [63]:
# 创建一个叫name的Series，里面包含字符串元素 "小陈", '小李', '小王', '小张', '小赵', '小周' ，标签为 '001', '002', '003', '004', '005', '006'
# 创建一个叫gender的Series，里面包含字符串元素 '女', '女', '男', '男', '女', '男' ， 标签为 '006', '005', '004', '003', '002', '001'
# 创建一个叫height的Series，里面包含浮点数元素 172.5, 168.0, 178.2, 181.3, 161.7 ， 标签为 '001', '002', '003', '004', '005'

In [6]:
name = pd.Series(["小陈", '小李', '小王', '小张', '小赵', '小周'], index=['001', '002', '003', '004', '005', '006'])
gender = pd.Series(['女', '女', '男', '男', '女', '男'], index=['006', '005', '004', '003', '002', '001'])
height = pd.Series([172.5, 168.0, 178.2, 181.3, 161.7], index=['001', '002', '003', '004', '005'])

In [7]:
# 创建一个叫students的DataFrame，包含列名姓名、性别、身高，数据分别对应创建好的name、gender和height，这三个Series，输出创建好的students

In [8]:
students = pd.DataFrame({'姓名': name, '性别': gender, '身高': height})    # 三个Series，根据索引对齐，进行合并
students

     姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7
006  小周  女    NaN

In [68]:
# 打印students所有索引和列名

In [72]:
print(students.index)
print('---------')
print(students.columns)

Index(['001', '002', '003', '004', '005', '006'], dtype='object')
---------
Index(['姓名', '性别', '身高'], dtype='object')

In [69]:
# 输出把students的行和列进行转置后的结果

In [73]:
students.T

      001    002    003    004    005  006
姓名     小陈     小李     小王     小张     小赵   小周
性别      男      女      男      男      女    女
身高  172.5  168.0  178.2  181.3  161.7  NaN

In [74]:
# 输出students的身高列

In [75]:
students.身高

001    172.5
002    168.0
003    178.2
004    181.3
005    161.7
006      NaN
Name: 身高, dtype: float64

In [77]:
students['身高']   # 若结合字符串，该方法更通用。例如，身高后面有空格如“身高 ”

001    172.5
002    168.0
003    178.2
004    181.3
005    161.7
006      NaN
Name: 身高, dtype: float64

In [78]:
# 输出students的性别和身高列

In [79]:
students[['性别', '身高']]

    性别     身高
001  男  172.5
002  女  168.0
003  男  178.2
004  男  181.3
005  女  161.7
006  女    NaN

In [80]:
# 输出students索引为003的行

In [82]:
students.loc['003']

姓名       小王
性别        男
身高    178.2
Name: 003, dtype: object

In [83]:
# 输出students索引为003、004、005的行

In [84]:
students.loc['003':'005']

     姓名 性别     身高
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7

In [85]:
# 输出students里索引为005的身高

In [86]:
students.loc['005','身高']

161.7

In [87]:
# 输出students索引为003、005的数据的姓名和身高

In [88]:
students.loc[['003', '005'], ['姓名', '身高']]

     姓名     身高
003  小王  178.2
005  小赵  161.7

In [ ]:
# 输出students索引为003、005的数据的所有变量

In [89]:
students.loc[['003', '005'], '姓名' : '身高']

     姓名 性别     身高
003  小王  男  178.2
005  小赵  女  161.7

In [90]:
students.loc[['003', '005'], :]

     姓名 性别     身高
003  小王  男  178.2
005  小赵  女  161.7

In [91]:
# 输出students里身高大于165的女性

In [93]:
students[(students['身高'] > 165) & (students['性别'] == '女')]

     姓名 性别     身高
002  小李  女  168.0

In [ ]:
# 通过head方法，输出students前五行数据

In [95]:
students.head()    # 默认值为5

     姓名 性别     身高
001  小陈  男  172.5
002  小李  女  168.0
003  小王  男  178.2
004  小张  男  181.3
005  小赵  女  161.7

# ----------------------------------------

In [9]:
# axis=0 表示纵向，1为横向

In [10]:
# 创建一个名为students的DataFrame，包含数据如下： 
# {"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},  "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},  
#  "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},  "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95},
#  "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},  "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92}  }
# 要求索引为学号（001、002等），列名为姓名、考试1、考试2、考试3，并输出创建好的DataFrame

In [11]:
student_data = {"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},  "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},  "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},  "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95}, "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},  "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92}  }
pd.DataFrame(student_data)

    001 002 003 004 005 006
姓名   小陈  小李  小王  小张  小赵  小周
考试1  85  91  86  79  96  81
考试2  95  92  81  89  91  89
考试3  92  94  89  95  91  92

In [15]:
students = pd.DataFrame(student_data).T
students

     姓名 考试1 考试2 考试3
001  小陈  85  95  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  89  95
005  小赵  96  91  91
006  小周  81  89  92

In [16]:
# 给students增加一列考试4，数据依次为：[72, 69, 79, 83, 82, 76]
students['考试4'] = [72, 69, 79, 83, 82, 76]
students

     姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  89  95   83
005  小赵  96  91  91   82
006  小周  81  89  92   76

In [19]:
# 方法二：
students['考试5'] = pd.Series([72, 69, 79, 83, 82, 76])    # 索引无法对其，索引输出的结果都是NaN
students

     姓名 考试1 考试2 考试3  考试4  考试5
001  小陈  85  95  92   72  NaN
002  小李  91  92  94   69  NaN
003  小王  86  81  89   79  NaN
004  小张  79  89  95   83  NaN
005  小赵  96  91  91   82  NaN
006  小周  81  89  92   76  NaN

In [20]:
# 对采用Series方法的修正
students['考试5'] = pd.Series([72, 69, 79, 83, 82, 76], index = ['001', '002', '003', '004', '005', '006'])
students

     姓名 考试1 考试2 考试3  考试4  考试5
001  小陈  85  95  92   72   72
002  小李  91  92  94   69   69
003  小王  86  81  89   79   79
004  小张  79  89  95   83   83
005  小赵  96  91  91   82   82
006  小周  81  89  92   76   76

In [21]:
# 给students添加一行，索引为007，数据为："小杨", 79, 82, 81, 69
students.loc["007"] = ["小杨", 79, 82, 81, 69, 69]        #——————————前提：添加行的列数需要与原DataFrame列数相同
students

     姓名 考试1 考试2 考试3  考试4  考试5
001  小陈  85  95  92   72   72
002  小李  91  92  94   69   69
003  小王  86  81  89   79   79
004  小张  79  89  95   83   83
005  小赵  96  91  91   82   82
006  小周  81  89  92   76   76
007  小杨  79  82  81   69   69

In [22]:
# 输出students删除索引006、007的结果，但不要改变students本身
students.drop(['006', '007'], axis=0)     # drop默认axis为0，只输出删除后的结果，原始的DataFrame不改变

     姓名 考试1 考试2 考试3  考试4  考试5
001  小陈  85  95  92   72   72
002  小李  91  92  94   69   69
003  小王  86  81  89   79   79
004  小张  79  89  95   83   83
005  小赵  96  91  91   82   82

In [24]:
# 输出students删除列名为"考试2"、"考试4"的结果，但不要改变students本身
students.drop(["考试2", "考试4"], axis=1)

     姓名 考试1 考试3  考试5
001  小陈  85  92   72
002  小李  91  94   69
003  小王  86  89   79
004  小张  79  95   83
005  小赵  96  91   82
006  小周  81  92   76
007  小杨  79  81   69

In [27]:
# 创建一个Series bonus，包含的值和值对应的索引分别为：{"考试1":2, "考试2":3, "考试3":2, "考试4":5}。
# 输出这个Series与students与students里所有分数列相加后的结果，但不要更新students
bonus = pd.Series({"考试1":2, "考试2":3, "考试3":2, "考试4":5})
bonus

考试1    2
考试2    3
考试3    2
考试4    5
dtype: int64

In [33]:
bonus + students[["考试1", "考试2", "考试3", "考试4"]]

    考试1 考试2 考试3  考试4
001  87  98  94   77
002  93  95  96   74
003  88  84  91   84
004  81  92  97   88
005  98  94  93   87
006  83  92  94   81
007  81  85  83   74

In [34]:
# 更新students的考试4，让每项数据值增加10，并输出更新后的结果
students["考试4"] + 10

001    82
002    79
003    89
004    93
005    92
006    86
007    79
Name: 考试4, dtype: int64

In [36]:
students["考试4"] = students["考试4"] + 10    # 赋值给students
students

     姓名 考试1 考试2 考试3  考试4  考试5
001  小陈  85  95  92   92   72
002  小李  91  92  94   89   69
003  小王  86  81  89   99   79
004  小张  79  89  95  103   83
005  小赵  96  91  91  102   82
006  小周  81  89  92   96   76
007  小杨  79  82  81   89   69

# -----------------------------------------------------------------

In [37]:
# apply函数，会被传到每行或每列
# applymap函数，会被运用到每一个元素上
# 以上均是返回一个新的DataFrame，原始的DataFrame不会被改变；且只能向里面传入数字

In [38]:
# describe方法，会自动忽视非数字列信息，只操作数字列信息，忽略非数字列的信息

In [39]:
# 创建一个名为students的DataFrame，包含数据如下： 
# {"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},  "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},  
#  "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},  "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95},
#  "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},  "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92}  }
# 要求索引为学号（001、002等），列名为姓名、考试1、考试2、考试3，并输出创建好的DataFrame

students = pd.DataFrame({"001": {"姓名": "小陈", "考试1": 85, "考试2": 95, "考试3": 92},  
                             "002": {"姓名": "小李", "考试1": 91, "考试2": 92, "考试3": 94},  
                             "003": {"姓名": "小王", "考试1": 86, "考试2": 81, "考试3": 89},  
                             "004": {"姓名": "小张", "考试1": 79, "考试2": 89, "考试3": 95}, 
                             "005": {"姓名": "小赵", "考试1": 96, "考试2": 91, "考试3": 91},  
                             "006": {"姓名": "小周", "考试1": 81, "考试2": 89, "考试3": 92}  }).T
students

     姓名 考试1 考试2 考试3
001  小陈  85  95  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  89  95
005  小赵  96  91  91
006  小周  81  89  92

In [40]:
# 创建一个students_average的DataFrame，索引为学号，包含姓名列（列名为“姓名”），以及计算出三次考试平均值后的结果列（列名为“平均分”）
average = students.loc[:, "考试1":"考试3"].mean(axis = 1)
name = students["姓名"]
students_average = pd.DataFrame({"姓名": name, "平均分": average})
students_average

     姓名        平均分
001  小陈  90.666667
002  小李  92.333333
003  小王  85.333333
004  小张  87.666667
005  小赵  92.666667
006  小周  87.333333

In [44]:
# 输出每次考试第二高的分数组成的Series，可以尝试结合匿名函数
students.loc[:, "考试1":"考试3"].apply(lambda x : np.sort(x)[-2])

考试1    91
考试2    92
考试3    94
dtype: int64

In [46]:
def get_grade(score):
    if score >= 95:
        return "A+"
    elif score >= 90:
        return "A"
    elif score >= 85:
        return "B+"
    elif score >= 80:
        return "B"
    elif score >= 75:
        return "C+"
    else:
        return "C"

In [47]:
students.loc[:, "考试1" : "考试2"] .applymap(get_grade)

    考试1 考试2
001  B+  A+
002   A   A
003  B+   B
004  C+  B+
005  A+   A
006   B  B+

In [48]:
# 展示students每个考试分数数据列的统计信息，包括个数、平均值、标准差、四分位数
students.describe()

        姓名  考试1  考试2  考试3
count    6    6    6    6
unique   6    6    5    5
top     小陈   85   89   92
freq     1    1    2    2

In [49]:
students["考试1"]

001    85
002    91
003    86
004    79
005    96
006    81
Name: 考试1, dtype: object

In [50]:
students["考试1"] = students["考试1"].astype("int")
students["考试2"] = students["考试2"].astype("int")
students["考试3"] = students["考试3"].astype("int")
students.describe()

             考试1        考试2        考试3
count   6.000000   6.000000   6.000000
mean   86.333333  89.500000  92.166667
std     6.314006   4.722288   2.136976
min    79.000000  81.000000  89.000000
25%    82.000000  89.000000  91.250000
50%    85.500000  90.000000  92.000000
75%    89.750000  91.750000  93.500000
max    96.000000  95.000000  95.000000